<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}" dir="{{ app()->isLocale('ar') ? 'rtl' : 'ltr' }}">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $project->title }} — {{ $project->category?->name }}</title>
    <meta name="description" content="{{ $project->short_description }}"><link rel="canonical" href="{{ route('projects.show', $project->slug) }}">
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500&display=swap" rel="stylesheet">
    @vite(['resources/css/portfolio.css', 'resources/js/portfolio.js'])
</head>
<body>
<header class="navbar"><div class="container nav-wrapper"><a href="{{ route('home') }}" class="brand-logo"><span>{{ $project->title }}</span><span class="brand-badge">&lt;/&gt; {{ __('ui.view_case_study') }}</span></a><div class="nav-actions"><a href="{{ route('locale.switch', ['locale' => app()->isLocale('ar') ? 'en' : 'ar']) }}" class="btn btn-secondary btn-sm">{{ __('ui.language') }}</a><a href="{{ route('home') }}#projects" class="btn btn-secondary btn-sm">{{ __('ui.back') }} {{ __('ui.projects') }}</a></div></div></header>
<main>
    <section class="hero-section"><div class="container"><div class="hero-kicker"><span class="kicker-line"></span><span>{{ $project->badge }}</span></div><h1 class="hero-title">{{ $project->title }}</h1><div class="hero-role">{{ $project->short_description }}</div><p class="hero-lead">{{ $project->full_description ?: $project->short_description }}</p>@if($project->imageUrl())<img src="{{ $project->imageUrl() }}" alt="{{ $project->title }}" style="max-width:100%;border-radius:1rem;margin-top:2rem">@endif<div class="hero-actions">@if($project->github_url)<a href="{{ $project->github_url }}" target="_blank" rel="noopener noreferrer" class="btn btn-primary">{{ __('ui.github') }}</a>@endif @if($project->live_demo_url)<a href="{{ $project->live_demo_url }}" target="_blank" rel="noopener noreferrer" class="btn btn-secondary">{{ __('ui.live_demo') }}</a>@endif</div></div></section>
    <section class="about-section"><div class="container"><div class="about-grid"><div class="about-text"><div class="section-header"><span class="section-tag">{{ __('ui.project') }}</span><h2 class="section-title">{{ $project->title }}</h2></div><p>{{ $project->full_description ?: $project->short_description }}</p>@if($project->case_study['problem'] ?? null)<div class="about-philosophy-card"><div class="about-philosophy-title">{{ __('ui.challenge') }}</div><div class="about-philosophy-text">{{ $project->case_study['problem'] }}</div></div>@endif</div><div class="about-specs"><div class="spec-item"><span class="spec-label">{{ __('ui.category') }}</span><span class="spec-val">{{ $project->category?->name }}</span></div><div class="spec-item"><span class="spec-label">{{ __('ui.status') }}</span><span class="spec-val">{{ $project->project_status }}</span></div><div class="spec-item"><span class="spec-label">{{ __('ui.client_company') }}</span><span class="spec-val">{{ $project->client_company ?: '—' }}</span></div><div class="spec-item"><span class="spec-label">{{ __('ui.dates') }}</span><span class="spec-val">{{ $project->start_date?->format('M Y') ?: '—' }} — {{ $project->completion_date?->format('M Y') ?: '—' }}</span></div></div></div></div></section>
    <section class="projects-section"><div class="container"><div class="section-header"><span class="section-tag">{{ __('ui.technology') }}</span><h2 class="section-title">{{ __('ui.tech_stack') }}</h2><p class="section-desc">{{ __('ui.technologies_used') }}</p></div><div class="project-tech-pills">@foreach($project->technologies as $technology)<span class="tech-pill">{{ $technology->name }}</span>@endforeach</div>@if($project->case_study['keyFeatures'] ?? null)<div class="modal-features-list" style="margin-top:2rem"><h3>{{ __('ui.key_features') }}</h3><ul>@foreach($project->case_study['keyFeatures'] as $feature)<li>{{ $feature }}</li>@endforeach</ul></div>@endif</div></section>
    @if($relatedProjects->isNotEmpty())<section class="projects-section"><div class="container"><div class="section-header"><span class="section-tag">{{ __('ui.more_work') }}</span><h2 class="section-title">{{ __('ui.related_projects') }}</h2></div><div class="projects-grid">@foreach($relatedProjects as $related)<article class="project-card"><div class="project-card-header"><span class="project-card-badge">{{ $related->badge }}</span><h3 class="project-card-title">{{ $related->title }}</h3><div class="project-card-subtitle">{{ $related->short_description }}</div></div><div class="project-card-actions"><a href="{{ route('projects.show', $related->slug) }}" class="btn btn-primary btn-sm">{{ __('ui.view_case_study') }}</a></div></article>@endforeach</div></div></section>@endif
</main>
</body>
</html>
